/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#include "AIRuntime[*Name*].h"


AIRuntime[*Name*]::~AIRuntime[*Name*]()
{
	[*arg-0*]
}

void AIRuntime[*Name*]::Init(AITaskData* data)
{
	AIBase::Init(data);
	[*arg-1*]
}


AIStatus AIRuntime[*Name*]::OnTick()
{
	[*arg-2*]
	return Success;
}