/*
 * <auto-generated>
 *	 此代码由工具生成 
 *	 手动更改此代码，可能会导致不正确的行为
 * </auto-generated>
 */
#pragma once
#include"NativeReader.h"
#include <vector>
#include"Log.h"

struct [*Table*]Row
{
	[**var**]
};

class [*Table*]:public NativeReader
{
public:
	[*Table*](void);
	void ReadTable();
	void GetRow(int val,[*Table*]Row* row);
	int GetLength();

protected:
	std::string name;
	std::vector<[*Table*]Row> m_data;
};


extern "C"
{
	ENGINE_INTERFACE_EXPORT int iGet[*Table*]Length();
	ENGINE_INTERFACE_EXPORT void iGet[*Table*]Row(int suitid,[*Table*]Row* row);
};