/*
 * <auto-generated>
 *	 The code is generated by tools
 *	 Edit manually this code will lead to incorrect behavior
 * </auto-generated>
 */

#ifndef __XNpcList__
#define __XNpcList__

#include "NativeReader.h"
#include "Log.h"
#include <vector>
#include <unordered_map>


struct XNpcListRow
{
	
	int npcid;
	char npcname[MaxStringSize];
	uint presentid;
	char npcicon[MaxStringSize];
	char npcportrait[MaxStringSize];
	int npcscene;
	float npcposition[MaxArraySize];
	float npcrotation[MaxArraySize];
	int requiredtaskid;
	char content[MaxStringSize];
	char functionlist[MaxStringSize];
	int gazing;
	bool onlyhead;
	char voice[MaxStringSize];
	char showup[MaxStringSize];
	int disappeartask;
	int npctype;
};

class XNpcList:public NativeReader
{
public:
	XNpcList(void);
	void ReadTable();
	void GetRow(int val,XNpcListRow* row);
	void GetByUID(uint id, XNpcListRow* row);
	int GetLength();

protected:
	std::string name;
	std::vector<XNpcListRow*> m_data;
	std::unordered_map<uint, XNpcListRow*> m_map;
};


extern "C"
{
	ENGINE_INTERFACE_EXPORT int iGetXNpcListLength();
	ENGINE_INTERFACE_EXPORT void iGetXNpcListRow(int idx,XNpcListRow* row);
	ENGINE_INTERFACE_EXPORT void iGetXNpcListRowByID(uint id, XNpcListRow* row);
};

#endif