// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AI.Runtime {
    using UnityEngine;
    
    
    public class AIRuntimeNavToTarget : AIRunTimeBase {
        
        public GameObject GameObjectmAIArgTarget;
        
        public GameObject GameObjectmAIArgNavTarget;
        
        public Vector3 Vector3mAIArgNavPos;
        
        public override void Init(AI.Runtime.AIRuntimeTaskData data) {
			base.Init(data);
			if(data.vars[1].val != null)
				GameObjectmAIArgNavTarget = (GameObject)data.vars[1].val;
			if(data.vars[2].val != null)
				Vector3mAIArgNavPos = (Vector3)data.vars[2].val;
        }
        
        public override AIRuntimeStatus OnTick(XEntity entity) {
			var inGameObjectmAIArgTarget = _tree.GetVariable("target"); 
			if (inGameObjectmAIArgTarget != null) GameObjectmAIArgTarget = (GameObject)inGameObjectmAIArgTarget;
			return AITreeImpleted.NavToTargetUpdate(entity, GameObjectmAIArgTarget, GameObjectmAIArgNavTarget, Vector3mAIArgNavPos);
        }
    }
}
