// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AI.Runtime {
    using UnityEngine;
    
    
    public class AIRuntimeWait : AIRunTimeBase {
        
        public float floatwaitTime;
        
        public bool boolrandomWait;
        
        public float floatrandomWaitMin;
        
        public float floatrandomWaitMax;
        
        public override void Init(AI.Runtime.AIRuntimeTaskData data) {
			base.Init(data);
			floatwaitTime = 34;
			boolrandomWait = false;
			floatrandomWaitMin = 1;
			floatrandomWaitMax = 1;
        }
        
        public override AIRuntimeStatus OnTick(XEntity entity) {
			return AITreeImpleted.WaitUpdate(entity, floatwaitTime, boolrandomWait, floatrandomWaitMin, floatrandomWaitMax);
        }
    }
}
