// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AI.Runtime
{


    //public class AIRuntimeFactory
    //{

    //    public static AIRunTimeBase MakeRuntime(AIRuntimeTaskData data)
    //    {
    //        AIRunTimeBase rst = null;
    //        switch (data.type)
    //        {
    //            case "Sequence":
    //                rst = new AIRuntimeSequence();
    //                break;
    //            case "Selector":
    //                rst = new AIRuntimeSelector();
    //                break;
    //            case "Inverter":
    //                rst = new AIRuntimeInverter();
    //                break;
    //        }
    //        if (rst != null) rst.Init(data);
    //        return rst;

    //    }
    //}
}
