// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AI.Runtime {
    using UnityEngine;
    
    
    public class AIRuntimeValueHP : AIRunTimeBase {
        
        public int mAIArgMaxHP;
        
        public int intmAIArgMinHP;
        
        public override void Init(AI.Runtime.AIRuntimeTaskData data) {
			base.Init(data);
			if(data.vars[0].val != null)
				mAIArgMaxHP = (System.Int32)data.vars[0].val;
        }
        
        public override AIRuntimeStatus OnTick(XEntity entity) {
			var inintmAIArgMinHP = _tree.GetVariable("minHP"); 
			if (inintmAIArgMinHP != null) intmAIArgMinHP = (System.Int32)inintmAIArgMinHP;
			return AITreeImpleted.ValueHPUpdate(entity, mAIArgMaxHP, intmAIArgMinHP);
        }
    }
}
