namespace XEditor
{
    public enum Trigger
    {
        ToEffect,
        ToIdle,
        ToWarriorSelect,
        ToWarriorShow,
        ToWarriorTurn,
        ToArcherSelect,
        ToArcherShow,
        ToArcherTurn,
        ToSorceressSelect,
        ToSorceressShow,
        ToSorceressTurn,
        ToClericSelect,
        ToClericShow,
        ToClericTurn,
        ToAcademicSelect,
        ToAcademicShow,
        ToAcademicTurn,
        ToAssassinSelect,
        ToAssassinShow,
        ToAssassinTurn,
        ToLogin,
        ToLoginEnter,
        ToSelectChar
    }
}
