/*
 * <auto-generated>
 *	 The code is generated by tools
 *	 Edit manually this code will lead to incorrect behavior
 * </auto-generated>
 */

#ifndef __FashionList__
#define __FashionList__

#include"NativeReader.h"
#include <vector>
#include"Log.h"

struct FashionListRow
{
	
	uint itemid;
	char itemname[MaxStringSize];
	int equippos;
	int profession;
	int level;
	char quality[MaxStringSize];
	char directorycomment[MaxStringSize];
	char modelprefabwarrior[MaxStringSize];
	char modelprefabarcher[MaxStringSize];
	char modelprefabsorcer[MaxStringSize];
	char modelprefabcleric[MaxStringSize];
	char modelprefab5[MaxStringSize];
	char modelprefab6[MaxStringSize];
	char modelprefab7[MaxStringSize];
	char modelprefab8[MaxStringSize];
	char presentid[MaxStringSize];
	int replaceid[MaxArraySize];
	char againreplaceid[MaxStringSize];
};

class FashionList:public NativeReader
{
public:
	FashionList(void);
	void ReadTable();
	void GetRow(int val,FashionListRow* row);
	int GetLength();

protected:
	std::string name;
	std::vector<FashionListRow> m_data;
};


extern "C"
{
	ENGINE_INTERFACE_EXPORT int iGetFashionListLength();
	ENGINE_INTERFACE_EXPORT void iGetFashionListRow(int idx,FashionListRow* row);
};

#endif