/*
 * <auto-generated>
 *	 The code is generated by tools
 *	 Edit manually this code will lead to incorrect behavior
 * </auto-generated>
 */

#ifndef __XEntityStatistics__
#define __XEntityStatistics__

#include"NativeReader.h"
#include <vector>
#include"Log.h"

struct XEntityStatisticsRow
{
	
	int uid;
	char name[MaxStringSize];
	uint presentid;
	int type;
	char tag[MaxStringSize];
	int fightgroup;
	char summongroup[MaxStringSize];
	float walkspeed;
	float runspeed;
	float floatheight[MaxArraySize];
	float rotatespeed;
	int attackspeed;
	int skillcd;
	float attackprob;
	float sight;
	float fighttogetherdis;
	char belocked[MaxStringSize];
	char inbornbuff[MaxStringSize];
	char maxsuperarmor[MaxStringSize];
	bool weakstatus;
	char superarmorbrokenbuff[MaxStringSize];
	int superarmorrecoveryvalue;
	int superarmorrecoverymax;
	int attackbase;
	int magicattackbase;
	float maxhp;
	int mobaexp;
	int mobaexprange;
	bool mobakillneedhint;
	int posindex;
	int hpsection;
	bool iswander;
	bool block;
	bool dynamicblock;
	bool usinggeneralcutscene;
	bool soloshow;
	bool endshow;
	int fov;
	float aistarttime;
	float aiactiongap;
	bool isfixedincd;
	int fashiontemplate;
	bool highlight;
	char usemymesh[MaxStringSize];
	char extrareward[MaxStringSize];
	int aihit;
	char aibehavior[MaxStringSize];
	int initenmity;
	bool alwayshpbar;
	bool hidename;
	float ratioleft;
	float ratioright;
	float ratioidle;
	float ratiodistance;
	float ratioskill;
	float ratioexp;
	char navigation[MaxStringSize];
	int isnavpingpong;
	bool hideinminimap;
	char access[MaxStringSize];
	char samebillboard[MaxStringSize];
	char pandoradropids[MaxStringSize];
	char dropids[MaxStringSize];
	char bigmeleepoints[MaxStringSize];
};

class XEntityStatistics:public NativeReader
{
public:
	XEntityStatistics(void);
	void ReadTable();
	void GetRow(int val,XEntityStatisticsRow* row);
	int GetLength();

protected:
	std::string name;
	std::vector<XEntityStatisticsRow> m_data;
};


extern "C"
{
	ENGINE_INTERFACE_EXPORT int iGetXEntityStatisticsLength();
	ENGINE_INTERFACE_EXPORT void iGetXEntityStatisticsRow(int idx,XEntityStatisticsRow* row);
};

#endif