/*
 * <auto-generated>
 *	 �˴����ɹ������� 
 *	 �ֶ����Ĵ˴��룬���ܻᵼ�²���ȷ����Ϊ
 * </auto-generated>
 */
#pragma once
#include"NativeReader.h"
#include <vector>
#include"Log.h"

struct XNpcList.csvRow
{
	
			int npcid;
			char npcname[MaxStringSize];
			uint presentid;
			char npcicon[MaxStringSize];
			char npcportrait[MaxStringSize];
			int npcscene;

			float npcposition[MaxArraySize];

			float npcrotation[MaxArraySize];
			int requiredtaskid;
			char content[MaxStringSize];
			char functionlist[MaxStringSize];
			int gazing;
			bool onlyhead;
			char voice[MaxStringSize];
			char showup[MaxStringSize];
			int disappeartask;
			int npctype;
};

class XNpcList.csv:public NativeReader
{
public:
	XNpcList.csv(void);
	void ReadTable();
	void GetRow(int val,XNpcList.csvRow* row);
	int GetLength();

protected:
	std::string name;
	std::vector<XNpcList.csvRow> m_data;
};


extern "C"
{
	ENGINE_INTERFACE_EXPORT int iGetXNpcList.csvLength();
	ENGINE_INTERFACE_EXPORT void iGetXNpcList.csvRow(int suitid,XNpcList.csvRow* row);
};