//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8784
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTable {
    
    
    public class QteStatusList : CVSReader {
        
        public class RowData {
			public string Comment;
			public string Name;
			public int Value;
		}


		private RowData[] Table;

		public override int length { get { return Table.Length; } }

		public RowData this[int index] { get { return Table[index]; } }

		public override string bytePath { get { return "Table/QteStatusList"; } }
        
        public override void OnClear(int lineCount) {
			if (lineCount > 0) Table = new RowData[lineCount];
			else Table = null;
        }
        
        public override void ReadLine(System.IO.BinaryReader reader) {
			RowData row = new RowData();
			Read<string>(reader, ref row.Comment, stringParse); columnno = 0;
			Read<string>(reader, ref row.Name, stringParse); columnno = 1;
			Read<int>(reader, ref row.Value, intParse); columnno = 2;
			Table[lineno] = row;
			columnno = -1;
        }
    }
}
