// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AI.Runtime {
    using UnityEngine;
    
    
    public class AIRuntimeWait : AIRunTimeBase {
        
        public float FloatwaitTime;
        
        public bool BoolrandomWait;
        
        public float FloatrandomWaitMin;
        
        public float FloatrandomWaitMax;
        
        public override AIRuntimeStatus OnTick(XEntity entity) {
			return AITreeImpleted.WaitUpdate(entity, FloatwaitTime, BoolrandomWait, FloatrandomWaitMin, FloatrandomWaitMax);
        }
    }
}
