/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#include "AIRuntimeStatusRandom.h"


AIRuntimeStatusRandom::~AIRuntimeStatusRandom()
{
	
}

void AIRuntimeStatusRandom::Init(AITaskData* data)
{
	AIBase::Init(data);
	Int32mAIArgProb = data->vars["Int32mAIArgProb"]->val.get<double>(); 
	
}


AIStatus AIRuntimeStatusRandom::OnTick(XEntity* entity)
{
	
	return AITreeImpleted::StatusRandomUpdate(entity,Int32mAIArgProb);
}