/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#include "AIRuntimeFindTargetByDistance.h"


AIRuntimeFindTargetByDistance::~AIRuntimeFindTargetByDistance()
{
	
}

void AIRuntimeFindTargetByDistance::Init(AITaskData* data)
{
	AIBase::Init(data);
	floatmAIArgDistance = data->vars["floatmAIArgDistance"]->val.get<double>(); 
	SinglemAIArgAngle = data->vars["SinglemAIArgAngle"]->val.get<double>(); 
	
}


AIStatus AIRuntimeFindTargetByDistance::OnTick(XEntity* entity)
{
	
	return AITreeImpleted::FindTargetByDistanceUpdate(entity,floatmAIArgDistance,SinglemAIArgAngle);
}