/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#include "AIRuntimeLog.h"


AIRuntimeLog::~AIRuntimeLog()
{
	
}

void AIRuntimeLog::Init(AITaskData* data)
{
	AIBase::Init(data);
	stringtext = data->vars["stringtext"]->val.get<std::string>(); 
	boollogError = data->vars["boollogError"]->val.get<bool>(); 
	
}


AIStatus AIRuntimeLog::OnTick(XEntity* entity)
{
	
	return AITreeImpleted::LogUpdate(entity,stringtext,boollogError);
}