/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#ifndef  __AIRuntimeValueHP__
#define  __AIRuntimeValueHP__

#include "../GameObject.h"
#include "../Vector3.h"
#include "../AIBehaviour.h"
#include "../AITreeImpleted.h"

class XEntity;

class AIRuntimeValueHP :public AIBase
{
public:
	~AIRuntimeValueHP();
	virtual void Init(AITaskData* data);
	virtual AIStatus OnTick(XEntity* entity);
	

private:
	int Int32mAIArgMaxHP;
	int Int32mAIArgMinHP;
	
};

#endif