/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#include "AIRuntimeStopNavMove.h"


AIRuntimeStopNavMove::~AIRuntimeStopNavMove()
{
	
}

void AIRuntimeStopNavMove::Init(AITaskData* data)
{
	AIBase::Init(data);
	
}


AIStatus AIRuntimeStopNavMove::OnTick(XEntity* entity)
{
	
	return AITreeImpleted::StopNavMoveUpdate(entity);
}