/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#ifndef  __AIRuntimeWait__
#define  __AIRuntimeWait__

#include "../GameObject.h"
#include "../Vector3.h"
#include "../AIBehaviour.h"
#include "../AITreeImpleted.h"

class XEntity;

class AIRuntimeWait :public AIBase
{
public:
	~AIRuntimeWait();
	virtual void Init(AITaskData* data);
	virtual AIStatus OnTick(XEntity* entity);
	

private:
	float floatwaitTime;
	bool boolrandomWait;
	float floatrandomWaitMin;
	float floatrandomWaitMax;
	
};

#endif