/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#include "AIRuntimeValueDistance.h"


AIRuntimeValueDistance::~AIRuntimeValueDistance()
{
	delete GameObjectmAIArgTarget;
}

void AIRuntimeValueDistance::Init(AITaskData* data)
{
	AIBase::Init(data);
	floatmAIArgMaxDistance = (float)data->vars["floatmAIArgMaxDistance"]->val.get<double>(); 
	
}


AIStatus AIRuntimeValueDistance::OnTick(XEntity* entity)
{
	GameObjectmAIArgTarget = _tree->GetGoVariable("target");
	
	return AITreeImpleted::ValueDistanceUpdate(entity,GameObjectmAIArgTarget,floatmAIArgMaxDistance);
}