/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#include "AIRuntimeResetTarget.h"


AIRuntimeResetTarget::~AIRuntimeResetTarget()
{
	
}

void AIRuntimeResetTarget::Init(AITaskData* data)
{
	AIBase::Init(data);
	
}


AIStatus AIRuntimeResetTarget::OnTick(XEntity* entity)
{
	
	return AITreeImpleted::ResetTargetUpdate(entity);
}