/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#ifndef  __AIRuntimeStatusRandom__
#define  __AIRuntimeStatusRandom__

#include "../ai/AIBehaviour.h"
#include "../GameObject.h"
#include "../Vector3.h"
#include "../ai/AITreeImpleted.h"

class XEntity;

class AIRuntimeStatusRandom :public AIBase
{
public:
	~AIRuntimeStatusRandom();
	virtual void Init(AITaskData* data);
	virtual AIStatus OnTick(XEntity* entity);
	

private:
	int Int32mAIArgProb;
	
};

#endif