/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#include "AIRuntimeMoveForward.h"


AIRuntimeMoveForward::~AIRuntimeMoveForward()
{
	
}

void AIRuntimeMoveForward::Init(AITaskData* data)
{
	AIBase::Init(data);
	
}


AIStatus AIRuntimeMoveForward::OnTick(XEntity* entity)
{
	
	return AITreeImpleted::MoveForwardUpdate(entity);
}