/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#include "AIRuntimeDoSelectNearest.h"


AIRuntimeDoSelectNearest::~AIRuntimeDoSelectNearest()
{
	
}

void AIRuntimeDoSelectNearest::Init(AITaskData* data)
{
	AIBase::Init(data);
	
}


AIStatus AIRuntimeDoSelectNearest::OnTick(XEntity* entity)
{
	
	return AITreeImpleted::DoSelectNearestUpdate(entity);
}