/*
* <auto-generated>
*	 The code is generated by tools
*	 Edit manually this code will lead to incorrect behavior
* </auto-generated>
*/

#ifndef  __AIRuntimeRotateToTarget__
#define  __AIRuntimeRotateToTarget__

#include "../AIBehaviour.h"
#include "../GameObject.h"
#include "../Vector3.h"


class AIRuntimeRotateToTarget :public AIBase
{
public:
	~AIRuntimeRotateToTarget();
	virtual void Init(AITaskData* data);
	virtual AIStatus OnTick();
	

private:
	GameObject* GameObjectmAIArgTarget;
	float floatmAIArgAngle;
	
};

#endif