//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8784
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTable {
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    
    
    public class CDefaultEquip {
        
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
		public struct RowData {
			uint profid;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string profname;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string face;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string hair;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string helmet;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string body;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string leg;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string glove;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string boots;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string weapon;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string secondweapon;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string wing;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string tail;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string decal;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string weaponpoint;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string wingpoint;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string tailpoint;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string fishingpoint;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string sideweaponpoint;

			public uint ProfID { get { return profid; } }

			public string ProfName { get { return profname; } }

			public string Face { get { return face; } }

			public string Hair { get { return hair; } }

			public string Helmet { get { return helmet; } }

			public string Body { get { return body; } }

			public string Leg { get { return leg; } }

			public string Glove { get { return glove; } }

			public string Boots { get { return boots; } }

			public string Weapon { get { return weapon; } }

			public string SecondWeapon { get { return secondweapon; } }

			public string Wing { get { return wing; } }

			public string Tail { get { return tail; } }

			public string Decal { get { return decal; } }

			public string WeaponPoint { get { return weaponpoint; } }

			public string WingPoint { get { return wingpoint; } }

			public string TailPoint { get { return tailpoint; } }

			public string FishingPoint { get { return fishingpoint; } }

			public string SideWeaponPoint { get { return sideweaponpoint; } }
		}


#if UNITY_IPHONE || UNITY_XBOX360
		[DllImport("__Internal")]
#else
		[DllImport("XTable")]
#endif
		static extern void iGetDefaultEquipRow(int idx, ref RowData row);

#if UNITY_IPHONE || UNITY_XBOX360
		[DllImport("__Internal")]
#else
		[DllImport("XTable")]
#endif
		static extern int iGetDefaultEquipLength();
        
        private static RowData m_data;
        
        public static int length {
            get {
				return iGetDefaultEquipLength();
            }
        }
        
        public static RowData GetRow(int idx) {
			iGetDefaultEquipRow(idx, ref m_data);
			return m_data;
        }
    }
}
