//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8825
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCore {
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    
    
    public class CEquipSuit {
        
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
		public struct RowData {
			int suitid;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string suitname;
			int level;
			int profid;
			int suitquality;
			bool iscreateshow;
			[MarshalAs(UnmanagedType.ByValArray, SizeConst = 16)]
			int[] equipid;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string effect1;
			[MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
			uint[] effect2;
			[MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
			uint[] effect3;
			[MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
			uint[] effect4;
			[MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
			uint[] effect5;
			[MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
			uint[] effect6;
			[MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
			uint[] effect7;
			[MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
			uint[] effect8;
			[MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
			uint[] effect9;
			[MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
			uint[] effect10;

			public int SuitID { get { return suitid; } }

			public string SuitName { get { return suitname; } }

			public int Level { get { return level; } }

			public int ProfID { get { return profid; } }

			public int SuitQuality { get { return suitquality; } }

			public bool IsCreateShow { get { return iscreateshow; } }

			public int[] Equipid { 
				get { 
					if (equipid.Length == 16) {
					List<int> list = new List<int>();
					for (int i = equipid.Length - 1; i >= 0; i--)
					{
						if (equipid[i] != 0) list.Add(equipid[i]);
					}
					equipid = list.ToArray();
					}
					 return equipid;
				}
			}

			public string Effect1 { get { return effect1; } }

			public CSeq< uint> Effect2{ get { return new CSeq< uint>(ref effect2); } }

			public CSeq< uint> Effect3{ get { return new CSeq< uint>(ref effect3); } }

			public CSeq< uint> Effect4{ get { return new CSeq< uint>(ref effect4); } }

			public CSeq< uint> Effect5{ get { return new CSeq< uint>(ref effect5); } }

			public CSeq< uint> Effect6{ get { return new CSeq< uint>(ref effect6); } }

			public CSeq< uint> Effect7{ get { return new CSeq< uint>(ref effect7); } }

			public CSeq< uint> Effect8{ get { return new CSeq< uint>(ref effect8); } }

			public CSeq< uint> Effect9{ get { return new CSeq< uint>(ref effect9); } }

			public CSeq< uint> Effect10{ get { return new CSeq< uint>(ref effect10); } }
		}


#if UNITY_IPHONE || UNITY_XBOX360
		[DllImport("__Internal")]
#else
		[DllImport("GameCore")]
#endif
		static extern void iGetEquipSuitRow(int idx, ref RowData row);

#if UNITY_IPHONE || UNITY_XBOX360
		[DllImport("__Internal")]
#else
		[DllImport("GameCore")]
#endif
		static extern void iGetEquipSuitRowByID(int idx, ref RowData row);

#if UNITY_IPHONE || UNITY_XBOX360
		[DllImport("__Internal")]
#else
		[DllImport("GameCore")]
#endif
		static extern int iGetEquipSuitLength();
        
        private static RowData m_data;
        
        public static int length {
            get {
				return iGetEquipSuitLength();
            }
        }
        
        public static RowData GetRow(int idx) {
			iGetEquipSuitRow(idx, ref m_data);
			return m_data;
        }
    }
}
