//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8784
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTable {
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    
    
    public class CEquipSuit {
        
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
		public struct RowData {
			int suitid;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string suitname;
			int level;
			int profid;
			int suitquality;
			bool iscreateshow;
			[MarshalAs(UnmanagedType.ByValArray, SizeConst = 16)]
			int[] equipid;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string effect1;
			CSeq<uint> effect2;
			CSeq<uint> effect3;
			CSeq<uint> effect4;
			CSeq<uint> effect5;
			CSeq<uint> effect6;
			CSeq<uint> effect7;
			CSeq<uint> effect8;
			CSeq<uint> effect9;
			CSeq<uint> effect10;

			public int SuitID { get { return suitid; } }

			public string SuitName { get { return suitname; } }

			public int Level { get { return level; } }

			public int ProfID { get { return profid; } }

			public int SuitQuality { get { return suitquality; } }

			public bool IsCreateShow { get { return iscreateshow; } }

			int[] Equipid { 
				get { 
					if (equipid.Length == 16) {
					List<int> list = new List<int>();
					for (int i = equipid.Length - 1; i >= 0; i--)
					{
						if (equipid[i] != -1) list.Add(equipid[i]);
					}
					equipid = list.ToArray();
					}
					 return equipid;
				}
			}

			public string Effect1 { get { return effect1; } }

			public CSeq<uint> Effect2{ get { return effect2; } }

			public CSeq<uint> Effect3{ get { return effect3; } }

			public CSeq<uint> Effect4{ get { return effect4; } }

			public CSeq<uint> Effect5{ get { return effect5; } }

			public CSeq<uint> Effect6{ get { return effect6; } }

			public CSeq<uint> Effect7{ get { return effect7; } }

			public CSeq<uint> Effect8{ get { return effect8; } }

			public CSeq<uint> Effect9{ get { return effect9; } }

			public CSeq<uint> Effect10{ get { return effect10; } }
		}


		[DllImport("XTable")]
		static extern void iGetEquipSuitRow(int idx, ref RowData row);

		[DllImport("XTable")]
		static extern int iGetEquipSuitLength();
        
        private static RowData m_data;
        
        public static int length {
            get {
				return iGetEquipSuitLength();
            }
        }
        
        public static RowData GetRow(int idx) {
			iGetEquipSuitRow(idx, ref m_data);
			return m_data;
        }
    }
}
