//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8825
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCore {
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    
    
    public class CQteStatusList {
        
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
		public struct RowData {
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string comment;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
			string name;
			int value;

			public string Comment { get { return comment; } }

			public string Name { get { return name; } }

			public int Value { get { return value; } }
		}


#if UNITY_IPHONE || UNITY_XBOX360
		[DllImport("__Internal")]
#else
		[DllImport("GameCore")]
#endif
		static extern void iGetQteStatusListRow(int idx, ref RowData row);

#if UNITY_IPHONE || UNITY_XBOX360
		[DllImport("__Internal")]
#else
		[DllImport("GameCore")]
#endif
		static extern int iGetQteStatusListLength();
        
        private static RowData m_data;
        
        public static int length {
            get {
				return iGetQteStatusListLength();
            }
        }
        
        public static RowData GetRow(int idx) {
			iGetQteStatusListRow(idx, ref m_data);
			return m_data;
        }
    }
}
